services:
  zaak-to-modulon:
    build:
      context: https://github.com/Achim-Sommer/ZaakToModulon.git#main
      dockerfile: Dockerfile
    container_name: zaak-to-modulon
    ports:
      - "9000:8000"
    environment:
      FLASK_RUN_HOST: 0.0.0.0
      FLASK_RUN_PORT: 8000
      FLASK_APP: app.main
    restart: unless-stopped